import { Header } from '@/components/Layout/components/Header'
import { useSession } from 'next-auth/react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, type FC, type ReactNode } from 'react'

type MainLayoutProps = {
  children: ReactNode
  isProtected?: boolean
}

export const MainLayout: FC<MainLayoutProps> = ({ children, isProtected }) => {
  const router = useRouter()
  const { data: session } = useSession()

  useEffect(() => {
    if (isProtected && session == null) {
      router.push('/').catch(() => {
        throw new Error()
      })
    }
  }, [])

  if (isProtected && session == null) {
    return null
  }

  return (
    <>
      <Head>
        <title>myposts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col bg-white text-black space-y-6">
        <Header />
        <main className="container flex-1">{children}</main>
      </div>
    </>
  )
}
