import { Header } from '@/components/Layout/components/Header'
import clsx from 'clsx'
import { useSession } from 'next-auth/react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState, type FC, type ReactNode } from 'react'

type MainLayoutProps = {
  children: ReactNode
  className?: string
  isProtected?: boolean
}

export const MainLayout: FC<MainLayoutProps> = ({
  children,
  className,
  isProtected,
}) => {
  const [_isProtected] = useState(isProtected)
  const { status } = useSession()
  const router = useRouter()

  useEffect(() => {
    if (_isProtected && status === 'unauthenticated') {
      router.push('/').catch(() => {
        throw new Error()
      })
    }
  }, [_isProtected, status, router])

  if (_isProtected && status !== 'authenticated') {
    return null
  }

  return (
    <>
      <Head>
        <title>myposts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col bg-white text-black space-y-6">
        <Header />
        <main className={clsx(className, 'container flex-1')}>{children}</main>
      </div>
    </>
  )
}
