name: Deploy

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  ORG_ID: ${{ secrets.ORG_ID }}
  PROJECT_ID: ${{ secrets.PROJECT_ID}}

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install --global vercel@latest
      - run: vercel
